# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: BuildAndTest

on: [push, pull_request]

jobs:
  industrial_ci:
    env:
      DOCKER_IMAGE: 'moveit/moveit:melodic-source'
      UPSTREAM_WORKSPACE: 'upstream.rosinstall'
      BEFORE_INSTALL_UPSTREAM_DEPENDENCIES_EMBED: 'set +u && source /root/ws_moveit/install/setup.bash && set -u'
      AFTER_RUN_TARGET_TEST: './.ci.prepare_codecov'
      TARGET_CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS='--coverage' -DCMAKE_CXX_FLAGS='--coverage'"
      ADDITIONAL_DEBS: 'lcov'
      CCACHE_DIR: "${{ github.workspace }}/.ccache"
      BASEDIR: ${{ github.workspace }}/.work
      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cache ccache
        uses: actions/cache@v2
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ github.sha }}  
          restore-keys: |
            ccache-
      - name: cache upstream_ws
        uses: pat-s/always-upload-cache@v2.1.3
        with:
          path: ${{ env.BASEDIR }}/upstream_ws
          key: upstream_ws-${{ hashFiles('upstream.rosinstall') }}-${{ github.run_id }}
          restore-keys: |
            upstream_ws-${{ hashFiles('upstream.rosinstall') }}
      - name: industrial_ci
        uses: 'ros-industrial/industrial_ci@master'
      - name: upaload test artifacts (on failure)
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-results
          path: ${{ env.BASEDIR }}/target_ws/**/test_results/**/*.xml
      - name: upaload codecov report
        uses: codecov/codecov-action@v1
        with:
          files: ${{ env.BASEDIR }}/coverage.info
